### ISSUE TITLE
[STYLE CHANGE] Improving the UI of contact us section

### ISSUE THREAD

**Issue by Mahitej28** [UBA-GCOEN/StichHub#339] opened 2023-06-20 18:02 UTC
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Hello I am Mahima Churi, a proud contributor at GSSoc '23 I would like to work o this issue by improving the UI of the `Contact us` section.
Also the `Get Started` button at the top of Navbar needs some improvement, it is not properly aligned with other sections of navbar:
![image](https://github.com/UBA-GCOEN/StichHub/assets/98276915/b363184f-7fec-47eb-9627-bfc1ec88ae1c)

If you think its legit, then do assign me this issue under GSSoc '23 with a level of PR as well

### Reason for Change:

Making it much more user friendly and attractive, also relatable to theme

### Current Styling:

None

### Proposed Styling:

None

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment] 2023-06-22 10:48
@Mahitej28 I guess this issue if already been resolved, check once, and close this issue if the issue is already been solved.

**Comment by Siddhant-Patil0203** [comment] 2023-06-22 10:50
@Mahitej28 how are you planning to improve the UI of the contact us section?

**Comment by Siddhant-Patil0203** [comment] 2023-06-22 15:13
@Mahitej28 looks cool, go for it

**Comment by Mahitej28** [comment] 2023-06-22 15:14
> @Mahitej28 looks cool, go for it

Sure @Siddhant-Patil0203

**Closed** 2023-06-24 21:13 UTC
Labels: gssoc23, UI/UX, level1, 🚧STATUS : in progress
